trigger:
  batch: true
  branches:
    include:
    - master
    - develop
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.16.3'
  displayName: 'Install Node.js'
- script: |
    npm install
    npm install sgmf-scripts
  displayName: 'Install node modules'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Creating dw.json"
      echo '{
          "hostname": "$(hostname)",
          "username": "$(username)",
          "password": "$(password)",
          "code-version": "$(code-version)"
      }' > dw.json
      echo "Created dw.json"
    failOnStderr: true
    displayName: 'Create SFCC Config JSON'
- script: |
    npm run uploadCartridge "app*, int*, bc*"
  displayName: 'Upload cartridges'